# Generated by Django 4.2.2 on 2023-06-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Houes',
            new_name='House',
        ),
    ]
