# Generated by Django 4.2.2 on 2023-06-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_houes_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveBigIntegerField(help_text='KRW'),
        ),
    ]
