# Generated by Django 4.2.2 on 2023-07-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video_file',
        ),
    ]
